[package]
name = "RubyCryptoSha"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rutie = "0.8.3"
sha2 = "0.10.1"

[lib]
name = "RubyCryptoSha"
crate-type = ["cdylib"]
